/**
 * Static block-index corpus (markdown collections + feeds) — generated by
 * `bun scripts/generate-static-block-index.ts` (~8 MB JSON, ~21k rows).
 *
 * Deferred behind a memoized Promise so non-analytics routes (journal,
 * playground, effort pages) don't pay the parse cost on first paint: the
 * JSON only lands in the browser when a consumer actually asks for it.
 * This loader is the single entry point — tests/dev-tools that need the
 * corpus eagerly can `await loadStaticBlockIndex()` themselves.
 */
import type { BlockIndexRow } from '@/types/storage';

let staticBlockIndexPromise: Promise<BlockIndexRow[]> | null = null;

export function loadStaticBlockIndex(): Promise<BlockIndexRow[]> {
    if (!staticBlockIndexPromise) {
        staticBlockIndexPromise = import(
            '@/generated/static-block-index.json'
        ).then((m) => m.default as BlockIndexRow[]);
    }
    return staticBlockIndexPromise;
}
