import { ICodeStatement } from './CodeStatement';
import { IMetric, MetricType } from './Metric';
import { MetricContainer } from './MetricContainer';
import { CodeMetadata } from './CodeMetadata';
import { TimeSpan } from './TimeSpan';
import type { IMetricSource, MetricFilter } from '../contracts/IMetricSource';

/**
 * Output statement types indicating what kind of result this represents.
 *
 * - 'segment': A timed portion of execution (e.g., a round, an effort interval)
 * - 'milestone': A notable event during execution (e.g., halfway point, personal record)
 * - 'system': Debug/diagnostic output from lifecycle events
 * - 'event': Tracks external stimuli or internal triggers
 * - 'group': Identified segment with children
 * - 'load': Initial script state
 * - 'compiler': Behavior configuration and setup
 * - 'analytics': Output generated by the analytics engine
 */
export type OutputStatementType =
  | 'segment'
  | 'milestone'
  | 'completion'
  | 'metric'
  | 'system'
  | 'event'
  | 'group'
  | 'load'
  | 'compiler'
  | 'analytics';

/**
 * IOutputStatement extends ICodeStatement to represent runtime-generated output.
 *
 * This is the return type of execution — what "came out" of running a statement.
 */
export interface IOutputStatement extends ICodeStatement, IMetricSource {
  readonly id: number;
  readonly outputType: OutputStatementType;
  readonly timeSpan: TimeSpan;
  readonly sourceStatementId?: number;
  readonly sourceBlockKey: string;
  readonly stackLevel: number;
  readonly metrics: MetricContainer;
  readonly metricMeta: Map<IMetric, CodeMetadata>;
  readonly completionReason?: string;
  readonly statement?: ICodeStatement;
  readonly timestamp?: number;
}

/**
 * Options for creating an OutputStatement.
 */
export interface OutputStatementOptions {
  /** Output type classification */
  outputType: OutputStatementType;

  /** Execution timing */
  timeSpan: TimeSpan;

  /** The block key that produced this output */
  sourceBlockKey?: string;

  /** Stack level (depth) when this output was emitted */
  stackLevel?: number;

  /** The source statement ID (optional) */
  sourceStatementId?: number;

  /** Runtime-collected metrics */
  metrics?: MetricContainer | IMetric[];

  /** Map of metrics to metadata */
  metricMeta?: Map<IMetric, CodeMetadata>;

  /** Reason the block completed (e.g., 'user-advance', 'forced-pop') */
  completionReason?: string;

  /** Parent output statement ID (for hierarchy) */
  parent?: number;

  /** Child output statement groups (for hierarchy) */
  children?: number[][];
}

/**
 * Concrete implementation of IOutputStatement.
 */
export class OutputStatement implements IOutputStatement, IMetricSource {
  private static nextId = 1000000;

  readonly id: number;
  readonly outputType: OutputStatementType;
  readonly timeSpan: TimeSpan;

  readonly sourceStatementId?: number;
  readonly sourceBlockKey: string;
  readonly stackLevel: number;
  readonly metrics: MetricContainer;
  readonly metricMeta: Map<IMetric, CodeMetadata>;

  readonly completionReason?: string;
  readonly parent?: number;
  readonly children: number[][];
  readonly isLeaf: boolean;
  readonly meta: CodeMetadata;
  readonly statement?: ICodeStatement;
  readonly timestamp?: number;

  constructor(
    optionsOrStatement: OutputStatementOptions | ICodeStatement,
    metricsArg?: MetricContainer | IMetric[],
    timestamp?: number,
  ) {
    if (
      optionsOrStatement &&
      'outputType' in optionsOrStatement &&
      'timeSpan' in optionsOrStatement
    ) {
      const options = optionsOrStatement as OutputStatementOptions;
      this.id = OutputStatement.nextId++;
      this.outputType = options.outputType;
      this.timeSpan = options.timeSpan;
      this.sourceBlockKey = options.sourceBlockKey ?? '';
      this.sourceStatementId = options.sourceStatementId;
      this.stackLevel = options.stackLevel ?? 0;
      this.metrics = MetricContainer.from(options.metrics, this.id);
      this.metricMeta = options.metricMeta ?? new Map();
      this.completionReason = options.completionReason;
      this.parent = options.parent;
      this.children = options.children ?? [];
      this.isLeaf = this.children.length === 0;
      this.meta = new CodeMetadata(0, 0, 0, 0);
    } else {
      const stmt = optionsOrStatement as ICodeStatement;
      this.id = OutputStatement.nextId++;
      this.statement = stmt;
      this.outputType = 'segment';
      this.timeSpan = { started: timestamp ?? Date.now() };
      this.sourceBlockKey = '';
      this.sourceStatementId = typeof stmt?.id === 'number' ? stmt.id : undefined;
      this.stackLevel = 0;
      this.metrics = MetricContainer.from(metricsArg, this.id);
      this.metricMeta = new Map();
      this.children = [];
      this.isLeaf = true;
      this.meta = stmt?.meta ?? new CodeMetadata(0, 0, 0, 0);
      this.timestamp = timestamp ?? Date.now();
    }
  }

  // ═══════════════════════════════════════════════════════════════
  // IMetricSource implementation
  // ═══════════════════════════════════════════════════════════════

  getDisplayMetrics(filter?: MetricFilter): IMetric[] {
    return this.metrics.getDisplayMetrics(filter);
  }

  getMetric(type: MetricType | string): IMetric | undefined {
    return this.metrics.getMetric(type);
  }

  getAllMetricsByType(type: MetricType | string): IMetric[] {
    return this.metrics.getAllMetricsByType(type);
  }

  hasMetric(type: MetricType | string): boolean {
    return this.metrics.hasMetric(type);
  }

  get rawMetrics(): IMetric[] {
    return this.metrics.rawMetrics;
  }

  /**
   * Reset the ID counter (useful for testing)
   */
  static resetIdCounter(startAt: number = 1000000): void {
    OutputStatement.nextId = startAt;
  }
}
