/**
 * Shared widget authoring contract.
 *
 * Widgets are registered by name and rendered for fenced blocks that use the
 * ```widget:<name> syntax. The JSON body stays the source of truth; the React
 * component only renders that source.
 */

import type React from 'react'

/** Parsed JSON object passed into a widget component. */
export type WidgetConfig = Record<string, unknown>

/** Props passed to every registered widget component. */
export interface WidgetProps {
  /** Parsed JSON object from the fenced widget body. */
  config: WidgetConfig
  /** Exact source text between the opening and closing fences. */
  rawContent: string
  /** Stable section identifier generated by section-state.ts. */
  sectionId: string
}

/** Registry of widget names to React components. */
export type WidgetRegistry = Map<string, React.ComponentType<WidgetProps>>
