#!/usr/bin/env bun
/**
 * capture-fixture.ts — CLI tool for snapshotting dialect output.
 *
 * Usage:
 *   bun run src/dialects/__tests__/capture-fixture.ts --dialect crossfit <<'EOF'
 *   (20) EMOM
 *     5 pullups
 *     10 pushups
 *   EOF
 *
 * Or inline:
 *   bun run src/dialects/__tests__/capture-fixture.ts --dialect crossfit --block "(20) EMOM :30"
 *
 * Output is JSON you can paste as a test fixture, then edit the `expect` section
 * to reflect desired behavior (broken things → mark with `it.failing`).
 */

import { parseWithDialect, snapshotMetrics } from './dialect-test-helpers';

// ──────────────────────────────────────────────────────────
// Argument parsing
// ──────────────────────────────────────────────────────────

const args = process.argv.slice(2);

function getArg(flag: string): string | undefined {
  const idx = args.indexOf(flag);
  return idx !== -1 ? args[idx + 1] : undefined;
}

const dialect = (getArg('--dialect') ?? 'crossfit') as any;
const inlineBlock = getArg('--block');

async function readStdin(): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) {
    chunks.push(Buffer.from(chunk));
  }
  return Buffer.concat(chunks).toString('utf-8').trim();
}

// ──────────────────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────────────────

const block = inlineBlock ?? (await readStdin());

if (!block) {
  console.error('Error: provide a block via --block "..." or stdin');
  process.exit(1);
}

try {
  const { statements } = parseWithDialect(block, dialect);

  const output = {
    _comment: 'Generated by capture-fixture.ts — edit `expect` to match desired behavior',
    dialect,
    block,
    statements: statements.map((stmt, i) => ({
      index: i,
      id: stmt.id,
      parent: stmt.parent,
      children: stmt.children,
      ...snapshotMetrics(stmt),
    })),
  };

  console.log(JSON.stringify(output, null, 2));
} catch (err) {
  console.error('Parse failed:', (err as Error).message);
  process.exit(1);
}
