// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'[QVQPOOO!^QPO'#CwO#eQPO'#CcOOQO'#Cc'#CcOOQO'#Cf'#CfOOQO'#Cg'#CgOOQO'#Ce'#CeO$iQPO'#CeO$qQPO'#CiOOQO'#Cw'#CwOOQO'#Cr'#CrO$yQPO'#CkOOQO'#Cl'#ClOOQO'#Cn'#CnOOQO'#Co'#CoOOQO'#Cp'#CpOOQO'#Cq'#CqOOQO'#Cm'#CmO%OQPO'#CmOOQO'#Cd'#CdOOQO'#Ct'#CtO&_QPO'#CbO%^QPO'#CbOOQO'#Cs'#CsQVQPOOO&fQPO,58xOOQO,59P,59PO&qQPO'#CjOOQO'#Cu'#CuO'PQPO,59TOOQO-E6u-E6uO'[QPO,59VOOQO,59X,59XOOQO-E6r-E6rOOQO,58|,58|O'gQPO,58|OOQO-E6q-E6qOOQO1G.d1G.dO'nQPO'#CvO'sQPO,59UOOQO-E6s-E6sOOQO1G.o1G.oO(RQPO1G.qPOQO1G.s1G.sOOQO1G.h1G.hOOQO,59b,59bOOQO-E6t-E6tOOQO7+$]7+$]",
  stateData: "(s~OnOS~ORPOTaO[UOpQOqROrSOsVOtTOuWOwZOxXOz[O{]O|^O}_O!O`O!PgO~OoiORkXTkX[kXpkXrkXskXtkXukXwkXxkXzkX{kX|kX}kX!OkX!PkX~ORVXTVX[VXpVXrVXsVXtVXuVXwVXxVXzVX{VX|VX}VX!OVX!PkX~O[jOtTO~ORlOTkO~OooO~OTpO|^O}_O!O`O~ORXOTaO[UOpXOrSOsVOtTOuWOwZOxXOz[O{]O|^O}_O!O`O~O!PrO~P%^ORuOSuOTuO~OpvOR^XT^Xv^X~ORlOTkOvyO~ORXOpXOxXO~O!P|O~P%^OT}O~OpvOR^aT^av^a~ORXOpXOxXOy!PO~Ozt[!O}{rsoxRpqT!Pno~",
  goto: "#wlPPmPPPmqu|!T![P|!f|||!j!q!q!q|!{#R#^#d#jTgOhTfOhZdOefhsZcOefhsZVOefhsYUOefhsRjVTlWmZbOefhsYaOefhsRpbQhORthSeOhSqesRsfQmWRxmQwkR!OwYYOefhsQnzRzo",
  nodeNames: "⚠ Program Property Identifier String Number Block Lap Fragment Duration Trend CollectibleTimer Timer Rounds Sequence Action Text Quantity AtSign Question DistanceUnit WeightUnit Effort",
  maxTerm: 47,
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData: "5b~RtXY#cYZ#t]^#ypq#cqr$Prs$ztu$Puv$Pvw$Pxy'ayz'fz{'k{|(h|}$P}!O(m!O!P(r!P!Q)x!Q![-W![!]-}!_!`$P!a!b.g!b!c.l!c!}/i!}#O/w#O#P$P#P#Q/|#Q#R0R#T#U/i#U#V1O#V#Y/i#Y#Z1t#Z#_/i#_#`2j#`#a3U#a#b3j#b#o/i~#hSn~XY#cYZ#t]^#ypq#c~#yO!P~~#|PYZ#t~$U[x~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q$P!_!`$P!b!c$P#O#P$P#Q#R$P~$}XOY$zZ]$z^r$zrs%js#O$z#O#P&[#P;'S$z;'S;=`'Z<%lO$z~%oXS~OY$zZ]$z^r$zrs%js#O$z#O#P&[#P;'S$z;'S;=`'Z<%lO$z~&_RO;'S$z;'S;=`&h;=`O$z~&kYOY$zZ]$z^r$zrs%js#O$z#O#P&[#P;'S$z;'S;=`'Z;=`<%l$z<%lO$z~'^P;=`<%l$z~'fOu~~'kOv~~'r[s~x~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q$P!_!`$P!b!c$P#O#P$P#Q#R$P~(mOq~~(rOp~~(w]x~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q$P!Q![)p!_!`$P!b!c$P#O#P$P#Q#R$P~)uPT~!Q![)p~)}[x~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q*s!_!`$P!b!c$P#O#P$P#Q#R$P~*zjz~x~OY,lZ],l^q,lqr*srt,ltu*suv*svw*swz,lz{*s{|,l|}*s}!O,l!O!P*s!P!Q*s!Q!_,l!_!`*s!`!b,l!b!c*s!c#O,l#O#P*s#P#Q,l#Q#R*s#R;'S,l;'S;=`-Q<%lO,l~,qTz~OY,lZ],l^;'S,l;'S;=`-Q<%lO,l~-TP;=`<%l,l~-]RT~!O!P-f!Q![-W![!]-l~-iP!Q![)p~-oP!Q![-r~-wQ[~!Q![-r![!]-l~.SQo~!Q![.Y!a!b.b~._P[~!Q![.Y~.gOt~~.lO|~~.s[{~x~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q$P!_!`$P!b!c$P#O#P$P#Q#R$P~/nRR~!Q![/i!c!}/i#T#o/i~/|Ow~~0ROy~~0Y[r~x~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q$P!_!`$P!b!c$P#O#P$P#Q#R$P~1TTR~!Q![/i!c!}/i#T#k/i#k#l1d#l#o/i~1kR!O~R~!Q![/i!c!}/i#T#o/i~1yTR~!Q![/i!c!}/i#T#h/i#h#i2Y#i#o/i~2aR}~R~!Q![/i!c!}/i#T#o/i~2oVR~!Q![/i!c!}/i#T#Z/i#Z#[1d#[#a/i#a#b2Y#b#o/i~3ZTR~!Q![/i!c!}/i#T#U/i#U#V1d#V#o/i~3qT}~R~!Q![/i!c!}/i#T#]/i#]#^4Q#^#o/i~4VTR~!Q![/i!c!}/i#T#`/i#`#a4f#a#o/i~4kTR~!Q![/i!c!}/i#T#X/i#X#Y4z#Y#o/i~5RT}~R~!Q![/i!c!}/i#T#g/i#g#h2Y#h#o/i",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 339
})
