// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'[QVQPOOO!ZQPO'#CwO#_QPO'#CcOOQO'#Cc'#CcOOQO'#Cf'#CfOOQO'#Cg'#CgOOQO'#Ce'#CeO$`QPO'#CeO$hQPO'#CiOOQO'#Cw'#CwOOQO'#Cr'#CrO$pQPO'#CkOOQO'#Cl'#ClOOQO'#Cn'#CnOOQO'#Co'#CoOOQO'#Cp'#CpOOQO'#Cq'#CqOOQO'#Cm'#CmO$uQPO'#CmOOQO'#Cd'#CdOOQO'#Ct'#CtO&RQPO'#CbO%TQPO'#CbOOQO'#Cs'#CsQVQPOOO&YQPO,58xOOQO,59P,59PO&eQPO'#CjOOQO'#Cu'#CuO&sQPO,59TOOQO-E6u-E6uO'OQPO,59VOOQO,59X,59XOOQO-E6r-E6rOOQO,58|,58|O'ZQPO,58|OOQO-E6q-E6qOOQO1G.d1G.dO'bQPO'#CvO'gQPO,59UOOQO-E6s-E6sOOQO1G.o1G.oO'uQPO1G.qPOQO1G.s1G.sOOQO1G.h1G.hOOQO,59b,59bOOQO-E6t-E6tOOQO7+$]7+$]",
  stateData: "(f~OnOS~ORPOTaO[UOpQOqROrSOsTOtWOvZOwXOy[Oz]O{^O|_O}`O!OgO~OoiORkXTkX[kXpkXrkXskXtkXvkXwkXykXzkX{kX|kX}kX!OkX~ORVXTVX[VXpVXrVXsVXtVXvVXwVXyVXzVX{VX|VX}VX!OkX~O[jOsTO~ORlOTkO~OooO~OTpO{^O|_O}`O~ORXOTaO[UOpXOrSOsTOtWOvZOwXOy[Oz]O{^O|_O}`O~O!OrO~P%TORuOSuOTuO~OpvOR^XT^Xu^X~ORlOTkOuyO~ORXOpXOwXO~O!O|O~P%TOT}O~OpvOR^aT^au^a~ORXOpXOwXOx!PO~Oys[}|zrowRpqT!Ono~",
  goto: "#wlPPmPPPmqu|!T![P|!f|||!j!q!q!q|!{#R#^#d#jTgOhTfOhZdOefhsZcOefhsZVOefhsYUOefhsRjVTlWmZbOefhsYaOefhsRpbQhORthSeOhSqesRsfQmWRxmQwkR!OwYYOefhsQnzRzo",
  nodeNames: "⚠ Program Property Identifier String Number Block Lap Fragment Duration Trend CollectibleTimer Timer Rounds Sequence Action Text Quantity AtSign Question DistanceUnit WeightUnit Effort",
  maxTerm: 46,
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData: "4e~RtXY#cYZ#t]^#ypq#cqr$Prs$ztu$Puv$Pvw$Pxy'ayz'fz{$P{|'k|}$P}!O'p!O!P'u!P!Q({!Q![,Z![!]-Q!_!`$P!a!b-j!b!c-o!c!}.l!}#O.z#O#P$P#P#Q/P#Q#R/U#T#U.l#U#V0R#V#Y.l#Y#Z0w#Z#_.l#_#`1m#`#a2X#a#b2m#b#o.l~#hSn~XY#cYZ#t]^#ypq#c~#yO!O~~#|PYZ#t~$U[w~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q$P!_!`$P!b!c$P#O#P$P#Q#R$P~$}XOY$zZ]$z^r$zrs%js#O$z#O#P&[#P;'S$z;'S;=`'Z<%lO$z~%oXS~OY$zZ]$z^r$zrs%js#O$z#O#P&[#P;'S$z;'S;=`'Z<%lO$z~&_RO;'S$z;'S;=`&h;=`O$z~&kYOY$zZ]$z^r$zrs%js#O$z#O#P&[#P;'S$z;'S;=`'Z;=`<%l$z<%lO$z~'^P;=`<%l$z~'fOt~~'kOu~~'pOq~~'uOp~~'z]w~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q$P!Q![(s!_!`$P!b!c$P#O#P$P#Q#R$P~(xPT~!Q![(s~)Q[w~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q)v!_!`$P!b!c$P#O#P$P#Q#R$P~)}jy~w~OY+oZ]+o^q+oqr)vrt+otu)vuv)vvw)vwz+oz{)v{|+o|})v}!O+o!O!P)v!P!Q)v!Q!_+o!_!`)v!`!b+o!b!c)v!c#O+o#O#P)v#P#Q+o#Q#R)v#R;'S+o;'S;=`,T<%lO+o~+tTy~OY+oZ]+o^;'S+o;'S;=`,T<%lO+o~,WP;=`<%l+o~,`RT~!O!P,i!Q![,Z![!],o~,lP!Q![(s~,rP!Q![,u~,zQ[~!Q![,u![!],o~-VQo~!Q![-]!a!b-e~-bP[~!Q![-]~-jOs~~-oO{~~-v[z~w~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q$P!_!`$P!b!c$P#O#P$P#Q#R$P~.qRR~!Q![.l!c!}.l#T#o.l~/POv~~/UOx~~/][r~w~qr$Ptu$Puv$Pvw$Pz{$P|}$P!O!P$P!P!Q$P!_!`$P!b!c$P#O#P$P#Q#R$P~0WTR~!Q![.l!c!}.l#T#k.l#k#l0g#l#o.l~0nR}~R~!Q![.l!c!}.l#T#o.l~0|TR~!Q![.l!c!}.l#T#h.l#h#i1]#i#o.l~1dR|~R~!Q![.l!c!}.l#T#o.l~1rVR~!Q![.l!c!}.l#T#Z.l#Z#[0g#[#a.l#a#b1]#b#o.l~2^TR~!Q![.l!c!}.l#T#U.l#U#V0g#V#o.l~2tT|~R~!Q![.l!c!}.l#T#].l#]#^3T#^#o.l~3YTR~!Q![.l!c!}.l#T#`.l#`#a3i#a#o.l~3nTR~!Q![.l!c!}.l#T#X.l#X#Y3}#Y#o.l~4UT|~R~!Q![.l!c!}.l#T#g.l#g#h1]#h#o.l",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 327
})
