// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "(WOVQPOOOOQO'#C_'#C_O[QPO'#C^QaQQOOOlQPO,58xOqQPO'#CbO|QPO'#ChO!RQPO'#CkQOQPOOQ!WQPOOQ!]QQOOO!eQQO'#CaOOQO1G.d1G.dOOQO'#Ce'#CeO!vQPO'#CcO!{QPO'#CcOOQO,58|,58|O#QQPO,58|O#YQPO,59SO#bQQO,59VO#gQPO'#CnO#lQQO,58{O#}QPO,58}O$SQPO,58}O$XQPO'#CpO$aQPO1G.hOOQO1G.h1G.hOOQO'#Cj'#CjOOQO1G.n1G.nO$iQPO1G.nO$qQPO1G.qOOQO,59Y,59YOOQO-E6l-E6lO$vQPO'#CfOOQO1G.i1G.iO#}QPO1G.iOOQO,59[,59[OOQO-E6n-E6nOOQO7+$S7+$SO%UQPO'#CqO%ZQPO7+$YOOQO7+$Y7+$YO%cQPO7+$]O%hQPO'#CoO%mQPO,59QO%mQPO,59QOOQO7+$T7+$TOOQO,59],59]OOQO-E6o-E6oOOQO<<Gt<<GtOOQO<<Gw<<GwO%xQPO,59ZOOQO-E6m-E6mO&WQPO1G.lOOQO1G.u1G.u",
  stateData: "&c~OhOS~OSPO~OiSO~O]UO`VOkTO~OSZO~OS]OW_On`O~OkbO~OocO~O`VO~O]UO`VO~OjdO]TX`TXfTXkTX~OifO~OS]O~OmhOnjO~OSkOnlO~OanO~OSoO~OjdO]Ta`TafTakTa~OSqO~OisO~OS]OW_O~OmhOnvO~OmwOnyO~OSzO~OZ}Ol{OmYXnYX~OSkO~OmwOn!RO~Op!SO~OS!TO~Ol{OmYanYa~OZ!WOlcamcanca~Ol{OmYinYi~O",
  goto: "#TfPPgjPmpsPy!QP!WP![!bPP!g!m!w!}RRORQOR[SRYRQaTRthS^ThRg_QrfR!OsTXRYQmbR!PwVWRXYQeZRpeQ|qS!U|!VR!V}QiaRuiQxmR!Qx",
  nodeNames: "⚠ Query Head Aggregator Word Metric Filters Filter Negate TagKey TagValue Star GroupBy By Dimension Rollup RollupDot Int",
  maxTerm: 32,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "&o~ReXY!dYZ!d]^!dpq!dqr!uxy!zyz#Pz{#U|}#Z}!O#`!O!P#t!Q![$q![!]%X!c!}#`#R#S#`#T#U#`#U#V%^#V#o#`#o#p&`#p#q&e#q#r&j~!iSh~XY!dYZ!d]^!dpq!d~!zOW~~#POo~~#UOp~~#ZOZ~~#`Om~P#eTSP}!O#`!Q![#`!c!}#`#R#S#`#T#o#`~#yPj~#f#g#|~$PP#c#d$S~$VP#`#a$Y~$]P#`#a$`~$cP#i#j$f~$iP#d#e$l~$qO`~R$xTaQSP}!O#`!Q![$q!c!}#`#R#S#`#T#o#`~%^Oi~R%cVSP}!O#`!Q![#`!c!}#`#R#S#`#T#m#`#m#n%x#n#o#`R&PT]QSP}!O#`!Q![#`!c!}#`#R#S#`#T#o#`~&eOk~~&jOl~~&oOn~",
  tokenizers: [0, 1],
  topRules: {"Query":[0,1]},
  tokenPrec: 0
})
