// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Query = 1,
  Head = 2,
  Aggregator = 3,
  Metric = 4,
  Filters = 5,
  Filter = 6,
  TagKey = 7,
  TagValue = 8,
  GroupBy = 9,
  Dimension = 10,
  Rollup = 11
