// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'bOVQPOOOOQO'#C_'#C_O[QPO'#C^QaQQOOOlQPO,58xOqQPO'#CaO|QPO'#CeO!RQPO'#CgQOQPOOQgQPOOQdQQOOO!WQQO'#C`OOQO1G.d1G.dOOQO'#Cc'#CcO!iQPO'#CbO!nQPO'#CbOOQO,58{,58{O!sQPO,58{O!{QPO,59PO#TQQO,59RO#YQPO'#ChO#_QQO,58zO#pQPO,58|O#uQPO,58|O#zQPO'#CiO$SQPO1G.gOOQO1G.g1G.gOOQO'#Cf'#CfOOQO1G.k1G.kO$[QPO1G.kO$dQPO1G.mOOQO,59S,59SOOQO-E6f-E6fO$iQPO'#CdOOQO1G.h1G.hO#pQPO1G.hOOQO,59T,59TOOQO-E6g-E6gOOQO7+$R7+$RO$tQPO'#CjO$yQPO7+$VOOQO7+$V7+$VO%RQPO7+$XOOQO,59O,59OOOQO7+$S7+$SOOQO,59U,59UOOQO-E6h-E6hOOQO<<Gq<<GqOOQO<<Gs<<Gs",
  stateData: "%W~OaOS~ObPO~OcSO~OeTOjUOkVO~ObZO~Ob]Of_Oi`O~OebO~OlcO~OddO_SXeSXjSXkSX~OcfO~Ob]O~OhhOijO~ObkOilO~OmnO~OboO~OddO_SaeSajSakSa~ObqO~OcsO~Ob]Of_O~OhhOivO~OhwOiyO~ObzO~Og{OhWXiWX~ObkO~OhwOi!PO~On!QO~O",
  goto: "!r_PP`cfilry!P!T!Z!`!f!lRRORQOR[SRYRQaTRthS^ThRg_QrfR|sTXRYQmbR}wVWRXYQeZRpeQiaRuiQxmR!Ox",
  nodeNames: "⚠ Query Head Aggregator Metric Filters Filter TagKey TagValue GroupBy Dimension Rollup",
  maxTerm: 30,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "&g~RdXY!aYZ!a]^!apq!aqr!rxy!wyz!|z{#R|}#W}!O#]!O!P#q!Q![$n![!]%U!c!}#]#R#S#]#T#U#]#U#V%Z#V#o#]#o#p&]#q#r&b~!fSa~XY!aYZ!a]^!apq!a~!wOf~~!|Ol~~#ROn~~#WOg~~#]Oh~P#bTbP}!O#]!Q![#]!c!}#]#R#S#]#T#o#]~#vPd~#f#g#y~#|P#c#d$P~$SP#`#a$V~$YP#`#a$]~$`P#i#j$c~$fP#d#e$i~$nOk~R$uTmQbP}!O#]!Q![$n!c!}#]#R#S#]#T#o#]~%ZOc~R%`VbP}!O#]!Q![#]!c!}#]#R#S#]#T#m#]#m#n%u#n#o#]R%|TjQbP}!O#]!Q![#]!c!}#]#R#S#]#T#o#]~&bOe~~&gOi~",
  tokenizers: [0, 1],
  topRules: {"Query":[0,1]},
  tokenPrec: 0,
  termNames: {"0":"⚠","1":"@top","2":"Head","3":"Aggregator","4":"Metric","5":"Filters","6":"Filter","7":"TagKey","8":"TagValue","9":"GroupBy","10":"Dimension","11":"Rollup","12":"(dot word)+","13":"(comma Filter)+","14":"(comma Dimension)+","15":"␄","16":"%mainskip","17":"whitespace","18":"word","19":"colon","20":"dot","21":"braceOpen","22":"negate","23":"star","24":"comma","25":"braceClose","26":"by","27":"rollupDot","28":"parenOpen","29":"int","30":"parenClose"}
})
