// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Query = 1,
  Head = 2,
  Aggregator = 3,
  Word = 4,
  Metric = 5,
  Filters = 6,
  Filter = 7,
  Negate = 8,
  TagKey = 9,
  TagValue = 10,
  Star = 11,
  GroupBy = 12,
  By = 13,
  Dimension = 14,
  Rollup = 15,
  RollupDot = 16,
  Int = 17
