import { CodeMetadata } from "./CodeMetadata";

/**
 * Enum representing the collection state of a fragment's value.
 * Used to track whether a fragment's value is fully specified or needs to be collected.
 */
export enum FragmentCollectionState {
  /** Value is fully specified (current default behavior) */
  Defined = 'defined',
  
  /** Value should be generated by runtime (e.g., elapsed time) */
  RuntimeGenerated = 'runtime-generated',
  
  /** Value should be collected from user input (e.g., actual reps, weight used) */
  UserCollected = 'user-collected',
  
  /** Value has been collected and populated */
  Collected = 'collected'
}

export interface ICodeFragment {
  readonly image?: string;
  readonly value?: any;
  readonly type: string; // Retained for now, will be replaced by fragmentType
  readonly meta?: CodeMetadata;
  readonly fragmentType: FragmentType;
  /** Collection state for collectible fragments. Defaults to 'defined' for fully specified values. */
  readonly collectionState?: FragmentCollectionState;
  // Pure data interface - no metric methods
}

export enum FragmentType {
  Timer = 'timer',
  Rep = 'rep',
  Effort = 'effort',
  Distance = 'distance',
  Rounds = 'rounds',
  Action = 'action',
  Increment = 'increment',
  Lap = 'lap',
  Text = 'text',
  Resistance = 'resistance'
}
