import { MetricBehavior } from "../../types/MetricBehavior";
import { CodeMetadata } from "./CodeMetadata";

/**
 * Enum representing the collection state of a fragment's value.
 * Used to track whether a fragment's value is fully specified or needs to be collected.
 */
export enum FragmentCollectionState {
  /** Value is fully specified (current default behavior) */
  Defined = 'defined',

  /** Value should be generated by runtime (e.g., elapsed time) */
  RuntimeGenerated = 'runtime-generated',

  /** Value should be collected from user input (e.g., actual reps, weight used) */
  UserCollected = 'user-collected',

  /** Value has been collected and populated */
  Collected = 'collected',

  /** Value is a hint or suggestion not strictly enforced */
  Hinted = 'hinted',

  /** Value is actively being tracked during execution */
  Tracked = 'tracked',

  /** Value is derived from analysis */
  Analyzed = 'analyzed'
}

/**
 * Origin of a fragment - where it was created.
 * 
 * - 'parser': Fragment created by the parser from source text
 * - 'compiler': Fragment synthesized by a compiler strategy
 * - 'runtime': Fragment generated during execution (e.g., elapsed time)
 * - 'user': Fragment collected from user input (e.g., actual reps completed)
 */
export type FragmentOrigin = 'parser' | 'compiler' | 'runtime' | 'user';

export interface ICodeFragment {
  readonly image?: string;
  readonly value?: unknown;
  readonly type: string; // Retained for now, will be replaced by fragmentType
  readonly meta?: CodeMetadata;
  readonly fragmentType: FragmentType;
  /** Collection state for collectible fragments. Defaults to 'defined' for fully specified values. */
  readonly collectionState?: FragmentCollectionState;
  /** Behavioral grouping describing the intent of the fragment. */
  readonly behavior?: MetricBehavior;

  /**
   * Origin of this fragment - where it was created.
   * Defaults to 'parser' for backwards compatibility.
   */
  readonly origin?: FragmentOrigin;

  /**
   * Block key that created/owns this fragment.
   * Present for runtime and user-collected fragments.
   */
  readonly sourceBlockKey?: string;

  /**
   * Timestamp when this fragment was created/recorded.
   * Present for runtime and user-collected fragments.
   */
  readonly timestamp?: Date;

  // Pure data interface - no metric methods
}

export enum FragmentType {
  Timer = 'timer',
  Rep = 'rep',
  Effort = 'effort',
  Distance = 'distance',
  Rounds = 'rounds',
  Action = 'action',
  Increment = 'increment',
  Lap = 'lap',
  Text = 'text',
  Resistance = 'resistance'
}
