import { ICodeStatement } from './CodeStatement';
import { IMetric, MetricType } from './Metric';
import { MetricContainer } from './MetricContainer';
import { CodeMetadata } from './CodeMetadata';
import { TimeSpan } from './TimeSpan';
import { IMetricSource, MetricFilter } from '../contracts/IMetricSource';

/**
 * Output statement types indicating what kind of result this represents.
 *
 * - 'segment': A timed portion of execution (e.g., a round, an effort interval)
 * - 'milestone': A notable event during execution (e.g., halfway point, personal record)
 * - 'system': Debug/diagnostic output from lifecycle events (push, pop, next, event-action)
 * - 'event': Tracks external stimuli or internal triggers (e.g., 'next', 'timer')
 * - 'group': Identified segment with children
 * - 'load': Initial script state
 * - 'compiler': Behavior configuration and setup
 * - 'analytics': Output generated by the analytics engine
 */
export type OutputStatementType = 'segment' | 'milestone' | 'completion' | 'metric' | 'system' | 'event' | 'group' | 'load' | 'compiler' | 'analytics';

/**
 * IOutputStatement extends ICodeStatement to represent runtime-generated output.
 * 
 * This is the **return type** of execution — what "came out" of running a statement.
 * While ICodeStatement represents the input (what was parsed), IOutputStatement
 * represents the output (what was executed, including timing and collected data).
 * 
 * ## Time terminology (docs/architecture/time-terminology.md)
 *
 * The canonical time data lives in the **metrics** array:
 * - `MetricType.Spans`   — **Time**: raw TimeSpan[] recordings the block tracks
 * - `MetricType.Elapsed` — **Elapsed**: Σ(end − start) per span (active time)
 * - `MetricType.Total`   — **Total**: lastEnd − firstStart (wall-clock bracket)
 * - `MetricType.Duration` — **Duration**: parser-defined planned target
 * - `MetricType.SystemTime` — **TimeStamp**: system Date.now() when logged
 *
 */
export interface IOutputStatement extends ICodeStatement, IMetricSource {
    readonly id: number;
    /** The type of output this statement represents */
    readonly outputType: OutputStatementType;

    /** Execution timing — when this output occurred */
    readonly timeSpan: TimeSpan;

    /** The source statement ID that triggered this output (if any) */
    readonly sourceStatementId?: number;

    /** The block key that produced this output */
    readonly sourceBlockKey: string;

    /**
     * Stack level (depth) when this output was emitted.
     * 0 = root block, 1 = first child, etc.
     * Used for visualizing output hierarchy.
     */
    readonly stackLevel: number;

    /**
     * Fragments on IOutputStatement are runtime-generated.
     * They should have `origin: 'runtime'` or `origin: 'user'`.
     */
    readonly metrics: MetricContainer;

    /** Metadata mapping for metrics. Each metrics can have an optional associated meta object. */
    readonly metricMeta: Map<IMetric, CodeMetadata>;

    /**
     * The reason this block completed, if applicable.
     * 
     * Propagated from the block's `completionReason` during unmount.
     * Enables downstream consumers to distinguish:
     * - `'user-advance'` — self-pop (user clicked next)
     * - `'forced-pop'` — parent-pop (parent timer expired)
     * - `'timer-expired'` — block's own timer completed
     * - `'rounds-complete'` — all rounds finished
     * 
     * Only present on `'completion'` output type.
     */
    readonly completionReason?: string;
}

/**
 * Options for creating an OutputStatement.
 * 
 * Time data should be provided through `metrics` (SpansMetric,
 * ElapsedMetric, TotalMetric).
 */
export interface OutputStatementOptions {
    /** Output type classification */
    outputType: OutputStatementType;

    /** Execution timing */
    timeSpan: TimeSpan;

    /** The block key that produced this output */
    sourceBlockKey: string;

    /** Stack level (depth) when this output was emitted */
    stackLevel: number;

    /** The source statement ID (optional) */
    sourceStatementId?: number;

    /** Runtime-collected metrics */
    metrics?: MetricContainer | IMetric[];

    /** Map of metrics to metadata */
    metricMeta?: Map<IMetric, CodeMetadata>;

    /** Reason the block completed (e.g., 'user-advance', 'forced-pop') */
    completionReason?: string;

    /** Parent output statement ID (for hierarchy) */
    parent?: number;

    /** Child output statement groups (for hierarchy) */
    children?: number[][];
}

/**
 * Concrete implementation of IOutputStatement.
 * Created by the runtime when a block unmounts.
 */
export class OutputStatement implements IOutputStatement, IMetricSource {
    private static nextId = 1000000; // Start at a high number to avoid collision with parsed statement IDs

    readonly id: number;
    readonly outputType: OutputStatementType;
    readonly timeSpan: TimeSpan;

    readonly sourceStatementId?: number;
    readonly sourceBlockKey: string;
    readonly stackLevel: number;
    readonly metrics: MetricContainer;
    readonly metricMeta: Map<IMetric, CodeMetadata>;

    readonly completionReason?: string;
    readonly parent?: number;
    readonly children: number[][];
    readonly isLeaf: boolean;
    readonly meta: CodeMetadata;

    constructor(options: OutputStatementOptions) {
        this.id = OutputStatement.nextId++;
        this.outputType = options.outputType;
        this.timeSpan = options.timeSpan;
        this.sourceBlockKey = options.sourceBlockKey;
        this.sourceStatementId = options.sourceStatementId;
        this.stackLevel = options.stackLevel;
        this.metrics = MetricContainer.from(options.metrics, this.id);
        this.metricMeta = options.metricMeta ?? new Map();
        this.completionReason = options.completionReason;
        this.parent = options.parent;
        this.children = options.children ?? [];
        this.isLeaf = this.children.length === 0;

        // Placeholder metadata — OutputStatements are runtime-generated, not parsed.
        this.meta = { line: 0, columnStart: 0, columnEnd: 0, startOffset: 0, endOffset: 0, length: 0 };
    }

    // ═══════════════════════════════════════════════════════════════
    // IMetricSource implementation
    // ═══════════════════════════════════════════════════════════════

    /**
     * Get display-ready metrics after precedence resolution.
     * For each MetricType present, returns metric from the highest-
     * precedence origin tier.
     */
    getDisplayMetrics(filter?: MetricFilter): IMetric[] {
        return this.metrics.getDisplayMetrics(filter);
    }

    /**
     * Get the highest-precedence single metrics of a given type.
     */
    getMetric(type: MetricType): IMetric | undefined {
        return this.metrics.getMetric(type);
    }

    /**
     * Get ALL metrics of a given type, sorted by precedence (highest first).
     * Unlike `getMetric()`, this returns every tier, not just the winning one.
     */
    getAllMetricsByType(type: MetricType): IMetric[] {
        return this.metrics.getAllMetricsByType(type);
    }

    /**
     * Check if any metrics of this type exists.
     */
    hasMetric(type: MetricType): boolean {
        return this.metrics.hasMetric(type);
    }

    /**
     * Raw, unfiltered metrics. No precedence resolution.
     * Returns a defensive copy so mutations don't affect internal state.
     */
    get rawMetrics(): IMetric[] {
        return this.metrics.rawMetrics;
    }

    /**
     * Reset the ID counter (useful for testing)
     */
    static resetIdCounter(startAt: number = 1000000): void {
        OutputStatement.nextId = startAt;
    }
}
