/**
 * Mixed-Timers Compliance Tests
 *
 * Verifies the mixed-timers runtime scenario:
 * "5:00 Run / 10 Burpees / *:30 Rest / :? Max Effort Pushups"
 *
 * Root cause note: The originally reported "Invalid runtime state" bug has been
 * resolved. The mixed-timers script runs end-to-end without errors. The script
 * compiles via GenericTimerStrategy (5:00 Run → Timer countdown, 10 Burpees →
 * effort, *:30 Rest → Timer forced-countdown, :? Sprint → Timer count-up) with
 * ExitBehavior(mode:'immediate', onNext:false, onEvents:['timer:complete']) for
 * forced blocks and ExitBehavior(mode:'immediate', onNext:true) for normal timers.
 *
 * Note: *:30 Rest compiles as blockType "Timer" (forced countdown via
 * GenericTimerStrategy), not "Rest" (auto-generated by RestBlockBehavior).
 */
import { it, expect } from 'bun:test';
import { describeCompliance, assertions } from '@/testing/script';
import { currentBlockType, anySystemPopHasReason, systemPopValues } from '../helpers/compliance-helpers';

// ===========================================================================
// 🟢 Mixed Timers — Sequential blocks with different timer types
// ===========================================================================
describeCompliance('🟢 Mixed Timers — 5:00 Run / 10 Burpees / *:30 Rest / :? Max Effort Pushups',
    '5:00 Run\n10 Burpees\n*:30 Rest\n:? Max Effort Pushups',
    (ctx) => {

    it('step 0: startSession → depth = 2 (SessionRoot + WaitingToStart)', async () => {
        const script = await ctx.compile();
        expect((await script.snapshot()).depth).toBe(2);
    });

    it('step 1: userNext → first timer starts (5:00 Run)', async () => {
        const script = await ctx.compile();
        await script.next();
        expect(await currentBlockType(await script.snapshot())).toMatch(/timer/i);
    });

    it('step 2: advance 5:00 → timer expires, advances to effort (10 Burpees)', async () => {
        const script = await ctx.compile();
        await script.next(); // start 5:00 Run
        await script.tick(300_000); // expire the timer
        const snap = await script.snapshot();
        expect(snap.depth).toBeGreaterThan(0);
    });

    it('step 3: userNext → skip effort, mount forced timer (*:30 Rest)', async () => {
        const script = await ctx.compile();
        await script.next(); // start 5:00 Run
        await script.tick(300_000); // expire timer → effort mounts
        await script.next(); // skip effort → forced timer mounts
        const snap = await script.snapshot();
        expect(snap.depth).toBeGreaterThan(0);
        // *:30 Rest compiles as blockType "Timer" (forced countdown via GenericTimerStrategy)
        expect(await currentBlockType(snap)).toMatch(/rest|timer/i);
    });

    it('step 4: forced timer (*:30 Rest) cannot be skipped', async () => {
        const script = await ctx.compile();
        await script.next(); // start 5:00 Run
        await script.tick(300_000); // expire timer → effort
        await script.next(); // skip effort → forced timer
        const depthBeforeSkip = (await script.snapshot()).depth;
        await script.next(); // attempt skip — should be no-op
        const snap = await script.snapshot();
        expect(snap.depth).toBe(depthBeforeSkip);
    });

    it('step 5: advance 30s → forced timer expires, mounts collectible timer', async () => {
        const script = await ctx.compile();
        await script.next(); // start 5:00 Run
        await script.tick(300_000); // expire timer → effort
        await script.next(); // skip effort → forced timer
        await script.tick(30_000); // expire forced timer → collectible timer mounts
        const snap = await script.snapshot();
        expect(snap.depth).toBeGreaterThan(0);
        expect(await currentBlockType(snap)).toMatch(/timer/i);
    });

    it('step 6: collectible timer can be completed by userNext', async () => {
        const script = await ctx.compile();
        await script.next(); // start 5:00 Run
        await script.tick(300_000); // expire timer → effort
        await script.next(); // skip effort → forced timer
        await script.tick(30_000); // expire forced timer → collectible timer
        await script.tick(10_000); // some elapsed time
        await script.next(); // complete collectible timer
        const snap = await script.snapshot();
        expect(snap.depth).toBe(0);
    });

    it('full run: all blocks complete end-to-end without error', async () => {
        const script = await ctx.compile();
        await script.next(); // start 5:00 Run
        await script.tick(300_000); // expire timer → effort
        await script.next(); // skip effort → forced timer
        await script.tick(30_000); // expire forced timer → collectible timer
        await script.tick(10_000); // some elapsed time
        await script.next(); // complete collectible timer
        const snap = await script.snapshot();
        expect(snap.depth).toBe(0);
        // Verify outputs were produced
        expect(assertions(snap).outputs().all().length).toBeGreaterThan(0);
    });

    it('all outputs are paired after full run', async () => {
        const script = await ctx.compile();
        await script.next(); // start 5:00 Run
        await script.tick(300_000); // expire timer → effort
        await script.next(); // skip effort → forced timer
        await script.tick(30_000); // expire forced timer → collectible timer
        await script.tick(10_000); // some elapsed time
        await script.next(); // complete collectible timer
        const snap = await script.snapshot();
        const unpaired = assertions(snap).outputs().assertPairedOutputs();
        expect(unpaired).toEqual([]);
    });
});
