/**
 * Static block-index corpus (markdown collections + feeds) — generated by
 * `bun scripts/generate-static-block-index.ts` (~8 MB JSON, ~21k rows).
 *
 * Deferred behind a memoized Promise so non-analytics routes (journal,
 * playground, effort pages) don't pay the parse cost on first paint: the
 * JSON only lands in the browser when a consumer actually asks for it.
 * This loader is the single entry point — tests/dev-tools that need the
 * corpus eagerly can `await loadStaticBlockIndex()` themselves.
 */
import type { BlockIndexRow, Note } from '@/types/storage';
import type { NoteQueryStore, BlockQueryStore } from '@bitcobblers/wod-wiki-engine';
import { extractFrontmatterTags } from '@/lib/frontmatter';
import { setSuggestionBinding, catalogIdsFromBlocks } from '@bitcobblers/wod-wiki-ui';
import { indexedDBService } from '@/services/db/IndexedDBService';

let staticBlockIndexPromise: Promise<BlockIndexRow[]> | null = null;
export function loadStaticBlockIndex(): Promise<BlockIndexRow[]> {
    if (!staticBlockIndexPromise) {
        staticBlockIndexPromise = import(
            '@/generated/static-block-index.json'
        ).then((m) => m.default as BlockIndexRow[]);
    }
    return staticBlockIndexPromise;
}

/**
 * Created-at timestamp for a feed entry's date key (`yyyy-mm-dd` from the
 * file path). Returns 0 (undated) for malformed keys — undated rows are
 * excluded from dated time windows but present in unbounded queries.
 */
export function feedDateToCreatedAt(dateKey: string): number {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(dateKey)) return 0;
    const ts = Date.parse(`${dateKey}T00:00:00Z`);
    return Number.isNaN(ts) ? 0 : ts;
}

/**
 * Tag → noteIds index over a block index's frontmatter rows. Static-corpus
 * notes declare tags only in frontmatter `tags:`; this recovers the mapping
 * the note store needs to answer `tags:` clauses (issue #853 — the store
 * previously returned an empty set for every tag).
 */
export function staticTagIndexFromBlocks(blocks: BlockIndexRow[]): Map<string, Set<string>> {
    const index = new Map<string, Set<string>>();
    for (const block of blocks) {
        if (block.dataType !== 'frontmatter') continue;
        for (const tag of extractFrontmatterTags(block.rawContent)) {
            const ids = index.get(tag);
            if (ids) ids.add(block.noteId);
            else index.set(tag, new Set([block.noteId]));
        }
    }
    return index;
}

/**
 * Pure projection of a block_index into static Notes — one Note per distinct
 * noteId, with a `catalog` field set to `noteId.split('/')[0]`. The catalog is
 * the directory the file lives under (e.g. `crossfit-girls` for collections,
 * `crossfit-programming` for feeds) and is what the Library's panel uses to
 * target the `+ Filter → Catalog` menu.
 */
export function staticNotesFromBlocks(blocks: BlockIndexRow[]): Note[] {
    const map = new Map<string, Note>();
    for (const block of blocks) {
        if (!map.has(block.noteId)) {
            map.set(block.noteId, {
                id: block.noteId,
                title: block.noteTitle,
                createdAt: block.createdAt,
                type: 'note',
                sourceId: block.sourceId,
                // Catalog: drop the `feeds/` wrapper for feed rows, then take the
                // first path segment. For collections (`<dir>/<file>`) the first
                // segment is the directory; for feeds (`feeds/<dir>/<date>/<file>`)
                // it would be `feeds`, which is not the catalog id the panel wants.
                catalog: (block.noteId.startsWith('feeds/') ? block.noteId.slice('feeds/'.length) : block.noteId).split('/')[0],
            });
        }
    }
    return Array.from(map.values());
}

let staticNotesPromise: Promise<Note[]> | null = null;
export function loadStaticNotes(): Promise<Note[]> {
    if (!staticNotesPromise) {
        staticNotesPromise = loadStaticBlockIndex().then(staticNotesFromBlocks);
    }
    return staticNotesPromise;
}

let staticTagIndexPromise: Promise<Map<string, Set<string>>> | null = null;
/**
 * Memoized tag → noteIds index over the static corpus, derived lazily so
 * the ~21k-row scan only runs when a `tags:` clause actually executes.
 */
export function loadStaticTagIndex(): Promise<Map<string, Set<string>>> {
    if (!staticTagIndexPromise) {
        staticTagIndexPromise = loadStaticBlockIndex().then(staticTagIndexFromBlocks);
    }
    return staticTagIndexPromise;
}

export const staticNoteStore: NoteQueryStore = {
    getAllNotes: () => loadStaticNotes(),
    getNoteIdsForTag: async (label) =>
        (await loadStaticTagIndex()).get(label) ?? new Set<string>(),
};

export const staticBlockStore: BlockQueryStore = {
    getAllBlocks: () => loadStaticBlockIndex(),
};

// ── Composer suggestion bindings ───────────────────────────────────────────

setSuggestionBinding('catalog', {
    load: async () => {
        const blocks = await loadStaticBlockIndex();
        const catalogIds = catalogIdsFromBlocks(blocks);
        return catalogIds.map((id) => ({ value: id, label: id }));
    },
    cache: 'static',
    open: false,
    emptyText: 'No catalogs in the static corpus',
});

setSuggestionBinding('tag', {
    load: async () => {
        const tagIndex = await loadStaticTagIndex();
        const staticTags = Array.from(tagIndex.keys());
        let userTags: string[] = [];
        try {
            const userNotes = await indexedDBService.getAllNotes();
            userTags = userNotes.flatMap((n) => n.tags ?? []);
        } catch {
            // IndexedDB not ready in isolated test environments
        }
        const merged = Array.from(new Set([...staticTags, ...userTags])).sort((a, b) => a.localeCompare(b));
        return merged.map((t) => ({ value: t, label: t }));
    },
    cache: { ttlMs: 30_000 },
    open: true,
    emptyText: 'No tags yet — type one to filter by it',
});
