name: create-release

on:
  workflow_call:
    inputs:
      tag-name:
        description: "The tag name"
        required: true
        type: string
      version:
        description: "The version type (major, minor, or patch)"
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: ./dist
      
      - name: Create package.json for publishing
        run: |
          # Copy the original package.json to the dist directory
          node -e "const pkg=require('./package.json'); pkg.version='${{ inputs.version }}'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2))"
          cp package.json ./dist/
          cp README.md ./dist/ || echo "No README.md found"
          cp LICENSE ./dist/ || echo "No LICENSE found"

      - name: Create GitHub Release
        id: create_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              target_commitish: "${{ github.sha }}",
              name: "${{ inputs.version }}",
              tag_name: "${{ inputs.tag-name }}",
              generate_release_notes: true
            });
            
            return { release_id: release.data.id };

      - name: Publish to npm
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
