name: Publish to Wiki

on:
  push:
    branches: [ main ]  # Change to your target branch
    paths: [ 'docs/**' ]  # Only run when files in docs/ change
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for better commit messages
    
    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Clone wiki repository
      run: |
        # Clone the wiki repository
        git clone https://github.com/${{ github.repository }}.wiki.git wiki-repo
      env:
        GITHUB_TOKEN: ${{ secrets.WIKI_TOKEN }}
    
    - name: Copy files to wiki
      run: |
        # Remove old wiki content (except .git)
        find wiki-repo -type f ! -path "*/\.git/*" -delete
        
        # Copy new content from docs directory
        cp -r docs/* wiki-repo/ 2>/dev/null || echo "No files to copy"
        
        # Handle different file types appropriately
        cd wiki-repo
        
        # Convert README.md to Home.md if it exists
        if [ -f "README.md" ]; then
          mv README.md Home.md
        fi
        
        # Ensure we have at least a Home page
        if [ ! -f "Home.md" ]; then
          echo "# Wiki Home" > Home.md
          echo "This wiki was automatically generated from the repository." >> Home.md
        fi
    
    - name: Commit and push to wiki
      run: |
        cd wiki-repo
        
        # Add all changes
        git add .
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Commit with informative message
        COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        git commit -m "Update wiki from docs/ - ${COMMIT_SHA}"
        
        # Push to wiki
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Summary
      run: |
        echo "✅ Wiki updated successfully!"
        echo "📖 View wiki at: https://github.com/${{ github.repository }}/wiki"
