name: Run Tests and Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Parse coverage report
      id: coverage
      run: |
        # Assuming lcov-report is generated in coverage/lcov.info
        COVERAGE=$(grep -A 1 "All files" coverage/lcov-report/index.html)
        echo "coverage=$COVERAGE" >> $GITHUB_ENV

    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        header: Coverage Report
        message: ${{ env.coverage }}